style main page
scumpoker/scrum-pocker pull request #1
Opened 2020-11-10 23:17 UTC by Cors1k

2020-11-11 22:51 UTC, RedtigerAV requested changes

2020-11-11 22:51 UTC, RedtigerAV commented on src/app/modules/main-page/main-page.component.html
> +    <button class="tab__item active" routerLink="create">Создать комнату</button>
надо так: class="tab__item" routerLinkActive="active". И для второй кнопки также

2020-11-11 22:51 UTC, RedtigerAV commented on src/styles/abstract/mixins/_sizes.scss
> +@mixin layout {
Лучше реализовать это через класс, и потом указывать его через @extend

2020-12-05 10:40 UTC, Cors1k commented on src/styles/abstract/mixins/_sizes.scss
> +@mixin layout {
fixed

2020-12-05 10:46 UTC, RedtigerAV approved these changes

2020-12-05 10:46 UTC, merged